<?php

namespace Container2B8hKsz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFetchCantonscanStatsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FetchCantonscanStatsCommand' shared autowired service.
     *
     * @return \App\Command\FetchCantonscanStatsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/FetchCantonscanStatsCommand.php';

        $container->privates['App\\Command\\FetchCantonscanStatsCommand'] = $instance = new \App\Command\FetchCantonscanStatsCommand(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));

        $instance->setName('app:fetch-cantonscan-stats');
        $instance->setDescription('Fetch Cantonscan /api/stats and insert (captured_at, value) per stat key (idempotent)');

        return $instance;
    }
}
