<?php

namespace Container2B8hKsz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupCantonscanSchemaCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\SetupCantonscanSchemaCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\SetupCantonscanSchemaCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:setup-cantonscan-schema', [], 'Create per-metric tables (captured_at, value) for all keys from Cantonscan /api/stats', false, #[\Closure(name: 'App\\Command\\SetupCantonscanSchemaCommand')] fn (): \App\Command\SetupCantonscanSchemaCommand => ($container->privates['App\\Command\\SetupCantonscanSchemaCommand'] ?? $container->load('getSetupCantonscanSchemaCommandService')));
    }
}
