<?php

namespace ContainerNtDLPtS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFetchCantonscanStatsCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\FetchCantonscanStatsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\FetchCantonscanStatsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:fetch-cantonscan-stats', [], 'Fetch Cantonscan /api/stats and insert rows (captured_at, value) per stat key', false, #[\Closure(name: 'App\\Command\\FetchCantonscanStatsCommand')] fn (): \App\Command\FetchCantonscanStatsCommand => ($container->privates['App\\Command\\FetchCantonscanStatsCommand'] ?? $container->load('getFetchCantonscanStatsCommandService')));
    }
}
