<?php

namespace ContainerNtDLPtS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetupCantonscanSchemaCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SetupCantonscanSchemaCommand' shared autowired service.
     *
     * @return \App\Command\SetupCantonscanSchemaCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/SetupCantonscanSchemaCommand.php';

        $container->privates['App\\Command\\SetupCantonscanSchemaCommand'] = $instance = new \App\Command\SetupCantonscanSchemaCommand(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->services['doctrine.dbal.default_connection'] ?? $container->load('getDoctrine_Dbal_DefaultConnectionService')));

        $instance->setName('app:setup-cantonscan-schema');
        $instance->setDescription('Create per-metric tables (captured_at, value) for all keys from Cantonscan /api/stats');

        return $instance;
    }
}
