<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2B8hKsz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2B8hKsz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2B8hKsz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2B8hKsz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2B8hKsz\App_KernelDevDebugContainer([
    'container.build_hash' => '2B8hKsz',
    'container.build_id' => '74d5b19c',
    'container.build_time' => 1762259299,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2B8hKsz');
