<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_stats_list' => [[], ['_controller' => 'App\\Controller\\StatsApiController::list'], [], [['text', '/api/stats']], [], [], []],
    'api_stats_metric' => [['metric'], ['_controller' => 'App\\Controller\\StatsApiController::metric'], [], [['variable', '/', '[^/]++', 'metric', true], ['text', '/api/stats']], [], [], []],
    'api_stats_metric_latest' => [['metric'], ['_controller' => 'App\\Controller\\StatsApiController::latest'], [], [['text', '/latest'], ['variable', '/', '[^/]++', 'metric', true], ['text', '/api/stats']], [], [], []],
    'App\Controller\StatsApiController::list' => [[], ['_controller' => 'App\\Controller\\StatsApiController::list'], [], [['text', '/api/stats']], [], [], []],
    'App\Controller\StatsApiController::metric' => [['metric'], ['_controller' => 'App\\Controller\\StatsApiController::metric'], [], [['variable', '/', '[^/]++', 'metric', true], ['text', '/api/stats']], [], [], []],
    'App\Controller\StatsApiController::latest' => [['metric'], ['_controller' => 'App\\Controller\\StatsApiController::latest'], [], [['text', '/latest'], ['variable', '/', '[^/]++', 'metric', true], ['text', '/api/stats']], [], [], []],
];
